"""
FastAPI application entry point.
"""
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pathlib import Path

from app.config import settings
from app.api.health import router as health_router
from app.api.clients import router as clients_router
from app.api.chat import router as chat_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown hooks."""
    print(f"[clientchatbot] Starting up (AI provider: {settings.ai_provider})")
    yield
    # Nothing to do on shutdown — messages are persisted synchronously per
    # request, so there's no buffer to flush.


app = FastAPI(
    title="Client Chatbot",
    description="AI-powered law firm client chatbot",
    version="0.1.0",
    lifespan=lifespan,
)

# CORS
origins = settings.cors_origins.split(",") if settings.cors_origins != "*" else ["*"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Routers
app.include_router(health_router)
app.include_router(clients_router)
app.include_router(chat_router)

# Static assets are inlined into app/static_assets.py (generated by
# scripts/bundle_static.py) so that Vercel's @vercel/python runtime bundles
# them reliably — it only ships files reachable via imports.
from fastapi.responses import HTMLResponse, Response
from app.static_assets import EMBED_HTML, WIDGET_JS, LOGO_PNG, LOGO_BUBBLE_PNG


@app.get("/")
async def serve_embed():
    return HTMLResponse(EMBED_HTML)


@app.get("/embed.html")
async def serve_embed_html():
    return HTMLResponse(EMBED_HTML)


@app.get("/widget.js")
async def serve_widget():
    return Response(
        content=WIDGET_JS,
        media_type="application/javascript",
        headers={"Cache-Control": "public, max-age=300"},
    )


@app.get("/logo.png")
async def serve_logo():
    if not LOGO_PNG:
        return Response(status_code=404)
    return Response(
        content=LOGO_PNG,
        media_type="image/png",
        headers={"Cache-Control": "public, max-age=86400"},
    )


@app.get("/logo-bubble.png")
async def serve_logo_bubble():
    if not LOGO_BUBBLE_PNG:
        return Response(status_code=404)
    return Response(
        content=LOGO_BUBBLE_PNG,
        media_type="image/png",
        headers={"Cache-Control": "public, max-age=86400"},
    )
